Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/Maintenance/PriceLines/UpdatePriceLineViewModel.cs
using FMConway.Services.PriceLines.Models;
using FMConway.Services.JobTypes.Models;
using FMConway.Services.VehicleTypes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.Maintenance.PriceLines
{
    public class UpdatePriceLineViewModel
    {
        public PriceLineModel PriceLine { get; set; }
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/WorkInstructions/RepeatWorkInstructionViewModel.cs
using FMConway.Services.WorkInstructions.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructions
{
    public class RepeatWorkInstructionViewModel
    {
        public Guid WorkInstructionID { get; set; }
        public Guid JobID { get; set; }
        public int WorkInstructionNumber { get; set; }
        public DateTime StartDate { get; set; }
        [Display(Name = "Task Details")]
        public string Comments { get; set; }
        public string EmployeeName { get; set; }
        public string TrafficManagementActivities { get; set; }
        public bool IsActive { get; set; }

        [Required]
        public string JobTypeID { get; set; }
        public IEnumerable<SelectListItem> JobType { get; set; }
        public Guid? InstallWIID { get; set; }
        public string InstallWI { get; set; }

        public Guid? ChecklistID { get; set; }
        public string Checklist { get; set; }

        public string Client { get; set; }
        public string ContractNumber { get; set; }
        public string SchemeTitle { get; set; }
        public string ContractTitle { get; set; }
        public DateTime sequenceStartDate { get; set; }
        public DateTime sequenceEndDate { get; set; }
        public string RepeatID { get; set; }
        public IEnumerable<SelectListItem> RepeatType { get; set; }
        public string WeekendInstructionID { get; set; }
        public IEnumerable<SelectListItem> WeekendInstruction { get; set; }
        public string DayFrequencyID { get; set; }
        public IEnumerable<SelectListItem> DayFrequency { get; set; }

        public IEnumerable<SelectListItem> JobTypes { get; set; }

        public bool Sunday { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }

        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }

        // the parameters to WorkInstructionServices.DuplicateWorkInstruction should really just be changed to a RepeatWorkInstructionModel.
        // for the time just going to pass the address in as its own model, but all these parameters should be refactored into a model class in future.
        public RepeatWorkInstructionAddressModel GetAddressModel()
        {
            var addressModel = new RepeatWorkInstructionAddressModel();
            addressModel.AddressLine1 = AddressLine1;
            addressModel.AddressLine2 = AddressLine2;
            addressModel.AddressLine3 = AddressLine3;
            addressModel.City = City;
            addressModel.County = County;
            addressModel.Postcode = Postcode;

            return addressModel;
        }
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/WorkInstructions/ShiftProgressVM.cs
using FMConway.Services.WorkInstructions.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructions
{
    public class ShiftProgressVM
    {
        public Guid WorkInstructionID { get; set; }
        public Guid ShiftID { get; set; }
        public int ShiftProgressID { get; set; }
        public DateTime StartedDate { get; set; }
        public int StartedHour { get; set; }
        public int StartedMin { get; set; }

        public IEnumerable<SelectListItem> ShiftProgresses { get; set; }
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/WorkInstructions/WorkInstructionPriceLineViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FMConway.Services.WorkInstructions.Models;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructions
{
    public class WorkInstructionPriceLineViewModel
    {
        public WorkInstructionPriceLineModel WorkInstructionPriceLine { get; set; }

        public WorkInstructionPriceLineViewModel()
        {
            WorkInstructionPriceLine = new WorkInstructionPriceLineModel();
        }
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/WorkInstructions/WorkInstructionViewModel.cs
using FMConway.Services.WorkInstructions.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructions
{
    public class WorkInstructionViewModel
    {
        public WorkInstructionModel WorkInstruction { get; set; }

        public int? FirstConeHour { get; set; }
        public int? FirstConeMin { get; set; }
        public int? LastConeHour { get; set; }
        public int? LastConeMin { get; set; }

        public int StartHour { get; set; }
        public int StartMin { get; set; }
        public int FinishHour { get; set; }
        public int FinishMin { get; set; }

        public Guid? ShiftID { get; set; }

        public bool ShowTasks { get; set; }

        public IEnumerable<SelectListItem> WorkInstructionStatus { get; set; }

        public Guid LoadingSheetTemplateID { get; set; }
        public IEnumerable<SelectListItem> LoadingSheetTemplates { get; set; }

        public Dictionary<Guid, string> Drawings { get; set; }
        public Dictionary<Guid, string> MethodStatements { get; set; }
        public Dictionary<Guid, string> ToolboxTalks { get; set; }

        public IEnumerable<SelectListItem> IsSuccessfulStates { get; set; }

        public IEnumerable<WorkInstructionDocument> UploadedDocuments { get; set; }
        public List<WorkInstructionDocument> Documents { get; set; }
        public List<Guid> DocumentsFromJob { get; set; }

        public List<WorkInstructionPriceLineModel> PriceLines { get; set; }
        public bool Invoiced { get; set; }

        public WorkInstructionViewModel()
        {
            DocumentsFromJob = new List<Guid>();
        }
    }

    public class NewWorkInstructionViewModel : WorkInstructionViewModel
    {
        //[Required(ErrorMessage = "Price Line is required")]
        public Guid? PriceLineFK { get; set; }
        public string PriceLineCode { get; set; }
        public string PriceLineDescription { get; set; }
        public decimal? PriceLineRate { get; set; }
        public string PriceLineNote { get; set; }
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/Controllers/WorkInstructionController.cs
using FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructions;
using FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructionDetails;
using FMConway.MVCApp.Attributes;
using FMConway.MVCApp.Bootstrap.Collections;
using FMConway.MVCApp.Bootstrap.Collections.Lookup;
using FMConway.MVCApp.Controllers;
using FMConway.MVCApp.Menu;
using FMConway.Services.Collections.Paging;
using FMConway.Services.Jobs.Interfaces;
using FMConway.Services.LoadingSheets.Interfaces;
using FMConway.Services.Maintenance;
using FMConway.Services.WorkInstructions.Interfaces;
using FMConway.Services.WorkInstructions.Models;
using FMConway.Services.WorkInstructionDetails.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using FMConway.Services.ErrorLogging.Interfaces;
using FMConway.Services.UserProfiles;
using Triangle.Membership.Services.Sql;
using FMConway.Services.Employees.Models;
using FMConway.Services.Employees.Interfaces;
using FMConway.Services.WorkInstructions.Extensions;
using FMConway.MVCApp.Extensions;
using FMConway.Services.Pdf.Services;
using FMConway.Services.Helpers;
using FMConway.Services.WorkInstructions.Enums;
using FMConway.MVCApp.Areas.Contract.ViewModels.Jobs;
using FMConway.Services.MethodStatements.Interfaces;
using FMConway.Services.MethodStatements.Services;
using FMConway.MVCApp.Areas.Contract.ViewModels.MethodStatements;

namespace FMConway.MVCApp.Areas.Contract.Controllers
{
    [Users(Users.UserTypes.Contractor)]
    [NavigationMenu("Tasks", 40, "fa fa-list-check", "Administrator, Supervisor, Manager, Tasks, Customer")]
    public class WorkInstructionController : BaseController
    {
        IWorkInstructionService _workInstructionService;
        IMaintenanceService _maintenanceService;
        ILoadingSheetService _loadingSheetService;
        IErrorLoggingService _errorLoggingService;
        IUserProfileService _userProfileService;
        IEmployeeService _employeeService;
        IJobService _jobService;
        PdfService _pdfService;
        IMethodStatementService _methodStatementService;

        public WorkInstructionController(IWorkInstructionService workInstructionService, IMaintenanceService maintenanceService, ILoadingSheetService loadingSheetService, IErrorLoggingService errorLoggingService, IUserProfileService userProfileService, IEmployeeService employeeService, IJobService jobService, PdfService pdfService, IMethodStatementService methodStatementService)
        {
            _workInstructionService = workInstructionService;
            _maintenanceService = maintenanceService;
            _loadingSheetService = loadingSheetService;
            _errorLoggingService = errorLoggingService;
            _userProfileService = userProfileService;
            _employeeService = employeeService;
            _jobService = jobService;
            _pdfService = pdfService;
            _methodStatementService = methodStatementService;
        }

        #region Work Instruction table actions
        Func<WorkInstructionModel, TableAction> updateAction = workInstruction =>
        {
            return new TableAction()
            {
                Url = "/Contract/WorkInstruction/Update/" + workInstruction.WorkInstructionID,
                Title = "Edit",
                IconClass = "icon-pencil"
            };
        };
        Func<WorkInstructionModel, TableAction> scheduleAction = workInstruction =>
        {
            return new TableAction()
            {
                Url = "/Operation/Schedule/New/" + workInstruction.WorkInstructionID,
                Title = "Add To Schedule",
                IconClass = "icon-plus"
            };
        };
        #endregion

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        [NavigationMenuItem(10, "fa fa-check")]
        public ActionResult Active()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        [NavigationMenuItem(20, "fa fa-ban")]
        public ActionResult Inactive()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult RepeatedWorkInstructions(Guid parentWIFK)
        {
            var wi = _workInstructionService.Single(parentWIFK);
            WorkInstructionViewModel model = new WorkInstructionViewModel()
            {
                WorkInstruction = wi
            };
            return View(model);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult ActiveWorkInstructionsForJob(int rowCount, int page, string query, Guid jobID)
        {
            PagedResults<WorkInstructionModel> results = _workInstructionService.GetActiveWorkInstructionsPaged(rowCount, page, HttpUtility.HtmlEncode(query), jobID);

            PagedTable model = WorkInstructionOverviewTableForJob(results, new List<Func<WorkInstructionModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult ActiveWorkInstructionsForJobRaw(Guid jobID)
        {
            List<WorkInstructionSimpleModel> results = _workInstructionService.GetActiveWorkInstructions(jobID);
            foreach (var res in results)
            {
                res.DateString = res.Date.ToString();
            }
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult UpdateWorkInstructionsToInvoied(string[] tasks)
        {
            var res = _workInstructionService.UpdateWorkInstructionsToInvoiced(tasks);

            return Json(res, JsonRequestBehavior.AllowGet);
        }


        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult JobHasCompleteWorkInstruction(Guid jobID)
        {
            bool result = _workInstructionService.JobHasCompleteWorkInstruction(jobID);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult ActiveWorkInstructions(int rowCount, int page, string query, Guid jobID)
        {
            PagedResults<WorkInstructionModel> results = _workInstructionService.GetActiveWorkInstructionsPaged(rowCount, page, HttpUtility.HtmlEncode(query), jobID);

            PagedTable model = WorkInstructionOverviewTable(results, new List<Func<WorkInstructionModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        public ActionResult ActiveWorkInstructionsAll(int rowCount, int page, string query)
        {
            var results = _workInstructionService.GetActiveWorkInstructionsAllPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = WorkInstructionOverviewTable(results, new List<Func<WorkInstructionModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        public ActionResult ActiveWorkInstructionsNew(int rowCount, int page, string query)
        {
            var results = _workInstructionService.GetActiveWorkInstructionsNewPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = WorkInstructionOverviewTable(results, new List<Func<WorkInstructionModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        public ActionResult ActiveWorkInstructionsScheduled(int rowCount, int page, string query)
        {
            var results = _workInstructionService.GetActiveWorkInstructionsScheduledPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = WorkInstructionOverviewTable(results, new List<Func<WorkInstructionModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        public ActionResult ActiveWorkInstructionsReady(int rowCount, int page, string query)
        {
            var results = _workInstructionService.GetActiveWorkInstructionsReadyPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = WorkInstructionOverviewTable(results, new List<Func<WorkInstructionModel, TableAction>>() { updateAction });

            model.RemoveColumn(ColumnHeaders.Engineers);
            model.RemoveColumn(ColumnHeaders.Vehicles);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        public ActionResult ActiveWorkInstructionsComplete(int rowCount, int page, string query)
        {
            var results = _workInstructionService.GetActiveWorkInstructionsCompletePaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = WorkInstructionOverviewTable(results, new List<Func<WorkInstructionModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions, Customer")]
        public ActionResult ActiveWorkInstructionsInvoiced(int rowCount, int page, string query)
        {

Bespoke/FMConway.MVCApp/Areas/Contract/Views/WorkInstruction/Active.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructions.WorkInstructionViewModel

@{
    ViewBag.Title = "Active Work Instructions";

    var isCustomer = User.IsInRole("Customer");
    var defaultTab = isCustomer ? "complete" : "current";
}

@section contentHeader
{
    <h1>Active Tasks</h1>
}

<div class="overview">
    <div class="primary-actions">
        
    </div>
   
    <div class="tabbable">
        <ul class="nav nav-tabs" id="widataTab" style="width: auto">
            <li class="@(defaultTab == "current" ? "active" : "")" @(isCustomer ? "style=display:none" : "")>
                <a href="#current" data-toggle="tab">All</a>
            </li>
            <li class="@(defaultTab == "ready" ? "active" : "")" @(isCustomer ? "style=display:none" : "")>
                <a href="#ready" data-toggle="tab">Ready To Schedule</a>
            </li>
            <li class="@(defaultTab == "scheduled" ? "active" : "")" @(isCustomer ? "style=display:none" : "")>
                <a href="#scheduled" data-toggle="tab">Scheduled</a>
            </li>
            <li class="@(defaultTab == "complete" ? "active" : "")">
                <a href="#complete" data-toggle="tab">Completed</a>
            </li>
            <li class="@(defaultTab == "invoiced" ? "active" : "")" @(isCustomer ? "style=display:none" : "")>
                <a href="#invoiced" data-toggle="tab">Invoiced</a>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane @(defaultTab == "current" ? "active" : "")" id="current">

            </div>
            <div class="tab-pane @(defaultTab == "ready" ? "active" : "")" id="ready">

            </div>
            <div class="tab-pane @(defaultTab == "scheduled" ? "active" : "")" id="scheduled">

            </div>
            <div class="tab-pane @(defaultTab == "complete" ? "active" : "")" id="complete">

            </div>
            <div class="tab-pane @(defaultTab == "invoiced" ? "active" : "")" id="invoiced">

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $('#widataTab a').click(function (e) {
                e.preventDefault();
                $(this).tab('show');
            });
        });

        var activeWorkInstructions = null;
        var completeWorkInstructions = null;
        var scheduledWorkInstructions = null;
        var readyWorkInstructions = null;

        $(function () {
            activeWorkInstructions = new triangle.ui.table('#current', '/Contract/WorkInstruction/ActiveWorkInstructionsAll', 50);
            completeWorkInstructions = new triangle.ui.table('#complete', '/Contract/WorkInstruction/ActiveWorkInstructionsComplete', 50);
            scheduledWorkInstructions = new triangle.ui.table('#scheduled', '/Contract/WorkInstruction/ActiveWorkInstructionsScheduled', 50);
            readyWorkInstructions = new triangle.ui.table('#ready', '/Contract/WorkInstruction/ActiveWorkInstructionsReady', 50);
            invoicedWorkInstructions = new triangle.ui.table('#invoiced', '/Contract/WorkInstruction/ActiveWorkInstructionsInvoiced', 50);
        });

    </script>
}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/WorkInstruction/RepeatWorkInstruction.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.WorkInstructions.RepeatWorkInstructionViewModel

@{
    ViewBag.Title = "Repeat Task";
}

@section contentHeader
{
    <h1>Repeat Task</h1>
}

<div class="workinstruction">
    @Bootstrap.Validation.ValidationSummary()
    @using (Bootstrap.BeginHorizontalForm(new { enctype = "multipart/form-data" }))
    {
        <div class="primary-actions">
            @Html.ActionLink("Cancel", "Update", "WorkInstruction", new { id = Model.WorkInstructionID }, new { @class = "btn" })
            <input type="submit" class="btn btn-primary" value="Save" />
            
        </div>
        <div class="masonry">
            <div class="span6 control-collection">
                <fieldset>
                    <legend>Task Details</legend>
                    @Html.HiddenFor(m => m.JobID)
                    @Html.HiddenFor(m => m.WorkInstructionID)

                    @Bootstrap.TextBoxFor(m => m.WorkInstructionNumber, new { disabled = "disabled", label = "Parent Work Instruction"})
                    @*@Bootstrap.TextBoxFor(m => m.StartDate, new { disabled = "disabled", label = "Parent Start Date"})*@
                    @Bootstrap.TextAreaFor(m => m.Comments, new { @class = "auto-resize" })
                    @Bootstrap.TextBoxFor(m => m.EmployeeName, new { disabled = "disabled" })
                    @*@Bootstrap.TextBoxFor(m => m.Location, new { disabled = "disabled" })*@
                    @*@Bootstrap.TextBoxFor(m => m.TrafficManagementActivities, new { })*@
                    @*@Bootstrap.TextBoxFor(m => m.JobType, new { disabled = "disabled" })*@
                    @Bootstrap.DropDownListFor(m => m.JobTypeID, Model.JobType, new { label = "Job Type" })
                    @*@Bootstrap.LookupFor(m => m.JobTypeID, m => m.JobType, "Job Type")*@
                    <div id="installWI">
                        @Bootstrap.LookupFor(m => m.InstallWIID, m => m.InstallWI, "Install")
                    </div>
                    @Bootstrap.LookupFor(m => m.ChecklistID, m => m.Checklist, "Checklist")
                    @Bootstrap.CheckBoxFor(m => m.IsActive)
                </fieldset>
            </div>
            <div class="span6 control-collection">
                <fieldset>
                    <legend>Job Details</legend>
                    @Bootstrap.TextBoxFor(m => m.Client, new { disabled = "disabled" })
                    @Bootstrap.TextBoxFor(m => m.ContractNumber, new { disabled = "disabled" })
                    @Bootstrap.TextBoxFor(m => m.ContractTitle, new { disabled = "disabled" })
                    @Bootstrap.TextBoxFor(m => m.SchemeTitle, new { disabled = "disabled" })                    
                </fieldset>
            </div>
            <div class="span6 control-collection">
                <fieldset>
                    <legend>Job Details</legend>
                    @Bootstrap.TextBoxFor(m => m.AddressLine1)
                    @Bootstrap.TextBoxFor(m => m.AddressLine2)
                    @Bootstrap.TextBoxFor(m => m.AddressLine3)
                    @Bootstrap.TextBoxFor(m => m.City)
                    @Bootstrap.TextBoxFor(m => m.County)
                    @Bootstrap.TextBoxFor(m => m.Postcode)
                </fieldset>
            </div>
            <div class="span6 control-collection">
                <fieldset>
                    <legend>Repeat Details</legend>
                    @Bootstrap.DatePickerFor(m => m.sequenceStartDate, new { label = "Effective From"})
                    <div id="sequenceEndDateBox">
                        @Bootstrap.DatePickerFor(m => m.sequenceEndDate, new { label = "Effective Until"})
                    </div>
                    @Bootstrap.DropDownListFor(m => m.RepeatID, Model.RepeatType, new { label = "Repeat Type" })
                    <div id="weekendBox">
                        @Bootstrap.DropDownListFor(m => m.WeekendInstructionID, Model.WeekendInstruction, new { label = "Weekend Behaviour" })
                    </div>
                    <div id="frequencyBox">
                        @Bootstrap.DropDownListFor(m => m.DayFrequencyID, Model.DayFrequency, new { label = "Select Frequency" })
                    </div>
                    <div id="weekdays">
                        @Bootstrap.CheckBoxFor(m => m.Sunday)
                        @Bootstrap.CheckBoxFor(m => m.Monday)
                        @Bootstrap.CheckBoxFor(m => m.Tuesday)
                        @Bootstrap.CheckBoxFor(m => m.Wednesday)
                        @Bootstrap.CheckBoxFor(m => m.Thursday)
                        @Bootstrap.CheckBoxFor(m => m.Friday)
                        @Bootstrap.CheckBoxFor(m => m.Saturday)   
                    </div>                 
                </fieldset>
            </div>
        </div> 
    }
</div>
@section scripts{
    <script type="text/javascript">

        $(function () {
            var repeat = $('#RepeatID');
            var weekend = $('#WeekendInstructionID');
            var day = $('#DayFrequencyID');

            //var jobTypeLookup = new triangle.ui.lookup("#JobTypeID" /*ID*/, "/Contract/Maintenance/GetJobTypesLookup" /*URL*/, 7/*RowCount*/, false /*IsMultiSelect*/);
            var checklistLookup = new triangle.ui.lookup("#ChecklistID" /*ID*/, "/Contract/Maintenance/GetJobTypeChecklistLookup" /*URL*/, 7/*RowCount*/, false /*IsMultiSelect*/);
            var installWI = new triangle.ui.lookup("#InstallWIID" /*ID*/, "/Contract/WorkInstruction/GetInstallWILookup" /*URL*/, 7/*RowCount*/, false /*IsMultiSelect*/);
            installWI.UrlParameters = {"jobID" : $('#WorkInstruction_JobID').val() };
            // job type and checklist
            $("#JobTypeID").on('change', function () {
                var jobType = $(this).find('option:selected').text();

                // show install wi
                if (jobType == 'De-install' || jobType == 'VMS - Install and De-install') {
                    $("#installWI").show();
                } else {
                    $("#installWI").hide();
                    $('#InstallWIID').val('');
                    $('#InstallWI').val('');
                }

                // checklist disabled (not required in any job type workflow)
                $("#ChecklistID-lookup").hide();

                //if (jobType == 'Maintenance') {
                //    $("#ChecklistID-lookup").show();
                //} else {
                //    $("#ChecklistID-lookup").hide();
                //    $('#ChecklistID').val('');
                //    $('#Checklist').val('');
                //}
            });

            // default hide
            $('#weekdays').hide();
            $('#weekendBox').hide();
            $('#frequencyBox').hide();

            // repeat
            repeat.on('change', function ()
            {
                console.log(repeat.val());
                if (repeat.val() == "1") {
                    $('#weekendBox').hide();
                    $('#weekdays').hide();
                    $('#frequencyBox').hide();
                    $('#sequenceEndDateBox').show();
                }
                else if (repeat.val() == "2")
                {
                    $('#weekendBox').show();
                    $('#weekdays').hide();
                    $('#frequencyBox').hide();
                    $('#sequenceEndDateBox').show();
                }
                else if (repeat.val() == "3") {
                    $('#weekendBox').hide();
                    $('#frequencyBox').show();
                    $('#weekdays').show();
                    $('#sequenceEndDateBox').show();
                }
                else if (repeat.val() == "5")
                {
                    $('#weekendBox').hide();
                    $('#frequencyBox').show();
                    $('#weekdays').show();
                    $('#sequenceEndDateBox').show();
                }
                else if (repeat.val() == "6")
                {
                    $('#weekendBox').hide();
                    $('#frequencyBox').hide();
                    $('#weekdays').hide();
                    $('#sequenceEndDateBox').hide();
                }
                else {
                    $('#weekendBox').hide();
                    $('#frequencyBox').hide();
                    $('#weekdays').hide();
                    $('#sequenceEndDateBox').show();
                }
            });

            // onload
            $("#JobTypeID").trigger('change');
        });
    </script>
}