Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/Accidents/AccidentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FMConway.Services.WorkInstructions.Models;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.Accidents
{
    public class AccidentViewModel
    {
        public Guid AccidentID { get; set; }
        public string AccidentDescription { get; set; }
        public DateTime AccidentDate { get; set; }
        public Guid? WorkInstructionID { get; set; }
        public Guid? JobID { get; set; }
        public string Registrations { get; set; }
        public string PersonsReporting { get; set; }
        public string Location { get; set; }
        public string PeopleInvolved { get; set; }
        public string Witnesses { get; set; }
        public string ActionTaken { get;set;}
        public Guid? ShiftID { get; set; }
        public bool IsActive { get; set; }
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/Controllers/JobController.cs
using FMConway.MVCApp.Areas.Contract.ViewModels.Jobs;
using FMConway.MVCApp.Attributes;
using FMConway.MVCApp.Bootstrap.Collections;
using FMConway.MVCApp.Bootstrap.Collections.Lookup;
using FMConway.MVCApp.Controllers;
using FMConway.MVCApp.Extensions;
using FMConway.MVCApp.Menu;
using FMConway.Services.Collections.Paging;
using FMConway.Services.ErrorLogging.Interfaces;
using FMConway.Services.ReasonCodes.Interfaces;
using FMConway.Services.ReasonCodes.Models;
using FMConway.Services.Jobs.Interfaces;
using FMConway.Services.Jobs.Models;
using FMConway.Services.Schemes.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace FMConway.MVCApp.Areas.Contract.Controllers
{
    [Users(Users.UserTypes.Contractor)]
    [NavigationMenu("Jobs", 30, "fa fa-clipboard-list", "Administrator, Supervisor, Manager, Jobs")]
    public class JobController : BaseController
    {
        IJobService _jobService;
        ISchemeService _schemeService;
        IErrorLoggingService _errorLoggingService;
        IReasonCodeService _reasonCodeService;

        public JobController(IJobService jobService, ISchemeService schemeService, IErrorLoggingService errorLoggingService, IReasonCodeService reasonCodeService)
        {
            _jobService = jobService;
            _schemeService = schemeService;
            _errorLoggingService = errorLoggingService;
            _reasonCodeService = reasonCodeService;
        }

        #region Job table actions
        Func<JobModel, TableAction> updateAction = job =>
        {
            return new TableAction()
            {
                Url = "/Contract/Job/Update/" + job.JobID,
                Title = "Edit",
                IconClass = "icon-pencil"
            };
        };

        Func<JobModel, TableAction> viewAction = job =>
        {
            return new TableAction()
            {
                Url = "/Contract/Job/Summary/" + job.JobID,
                Title = "View",
                IconClass = "icon-eye-open"
            };
        };
        #endregion

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        [NavigationMenuItem(10, "fa fa-bolt")]
        public ActionResult LiveHires()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        [NavigationMenuItem(10, "fa fa-check-to-slot")]
        public ActionResult Completed()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        [NavigationMenuItem("Cancelled / Aborted", 20, "fa fa-xmark")]
        public ActionResult Cancelled()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        public ActionResult LiveHireJobs(int rowCount, int page, string query)
        {
            PagedResults<JobModel> results = _jobService.GetLiveHireJobsPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = JobOverviewTable(results, new List<Func<JobModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        public ActionResult CompletedJobs(int rowCount, int page, string query)
        {
            PagedResults<JobModel> results = _jobService.GetCompleteJobsPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = JobOverviewTable(results, new List<Func<JobModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        public ActionResult ActiveJobsForScheme(int rowCount, int page, string query, Guid schemeID)
        {
            PagedResults<JobModel> results = _jobService.GetActiveJobsForSchemePaged(rowCount, page, HttpUtility.HtmlEncode(query), schemeID);

            PagedTable model = JobOverviewForSchemaTable(results, new List<Func<JobModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        public ActionResult InactiveJobs(int rowCount, int page, string query)
        {
            PagedResults<JobModel> results = _jobService.GetInactiveJobsPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = JobOverviewTable(results, new List<Func<JobModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        private PagedTable JobOverviewTable(PagedResults<JobModel> results, List<Func<JobModel, TableAction>> actions)
        {
            PagedTable model = new PagedTable()
            {
                Page = results.Page,
                PageCount = results.PageCount,
                ColumnHeaders = new string[]
                {
                    "Job Number",
                    "Contract Number",
                    "Sub Department", //Depot
                    "Customer Project Code",
                    "Customer",
                    "Contract Manager",
                    "Contract / Scheme",
                    "Title",
                    "Start",
                    "Finish",
                    "Description",
                    "Phone",
                    "Address"
                },
                Rows = results.Data.Select(s => new TableRow
                {
                    TableData = new string[]
                    {
                        s.JobNumber.ToString(),
                        s.ContractNumber,
                        s.DepotLookup,
                        s.CustomerProjectCode,
                        s.Customer,
                        s.ContractsManager,
                        s.SchemeID.HasValue ? s.Scheme.SchemeTitle : s.ContractTitle,
                        s.JobTitle,
                        s.StartDate.ToShortDateString(),
                        s.EndDate?.ToShortDateString(),
                        s.Description,
                        s.CustomerPhone,
                        JobModelToInlineAddress(s)
                    },
                    Actions = actions.Select(action => action(s)).ToList()
                }).ToList()
            };

            return model;
        }

        private PagedTable JobOverviewForSchemaTable(PagedResults<JobModel> results, List<Func<JobModel, TableAction>> actions)
        {
            PagedTable model = new PagedTable()
            {
                Page = results.Page,
                PageCount = results.PageCount,
                ColumnHeaders = new string[]
                {
                    "Job Number",
                    "Contract Number",
                    "Customer",
                    "Contract Manager",
                    "Title",
                    "Start",
                    "Finish",
                    "Phone"
                },
                Rows = results.Data.Select(s => new TableRow
                {
                    TableData = new string[]
                    {
                        s.JobNumber.ToString(),
                        s.ContractNumber,
                        s.Customer,
                        s.ContractsManager,
                        s.JobTitle,
                        s.StartDate.ToShortDateString(),
                        s.EndDate?.ToShortDateString(),
                        s.CustomerPhone
                    },
                    Actions = actions.Select(action => action(s)).ToList()
                }).ToList()
            };

            return model;
        }

        private string JobModelToInlineAddress(JobModel model)
        {
            return String.Join(" ", new[]
            {
                model.AddressLine1,
                model.AddressLine2,
                model.AddressLine3,
                model.City,
                model.County,
                model.Postcode
            }.Where(a => !String.IsNullOrWhiteSpace(a)));
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        [NavigationMenuItem(30, "fa-regular fa-pen-to-square")]
        public ActionResult New(Guid? schemeID)
        {
            JobViewModel model = new JobViewModel();

            model.Job = new JobModel()
            {
                StartDate = DateTime.Today,
                EndDate = DateTime.Today
            };

            if (schemeID != null)
            {
                var schemeAddress = _schemeService.Single((Guid)schemeID);
                model.Job.AddressLine1 = schemeAddress.AddressLine1;
                model.Job.AddressLine2 = schemeAddress.AddressLine2;
                model.Job.AddressLine3 = schemeAddress.AddressLine3;
                model.Job.City = schemeAddress.City;
                model.Job.County = schemeAddress.County;
                model.Job.Postcode = schemeAddress.Postcode;
            }

            model.IsSuccessfulStates = SelectListExtensions.NullableYesNoCheckBox();

            if (schemeID.HasValue)
            {
                model.Job.SchemeID = schemeID.Value;
                model.Job.Scheme = _schemeService.Single(schemeID.Value);
            }

            return View(model);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Jobs")]
        [HttpPost]
        public ActionResult New(JobViewModel model)
        {
            List<JobDocument> documents = TempData["SubmittedDocuments"] as List<JobDocument>;

            if (documents == null)
                documents = new List<JobDocument>();

            if (model.UploadedDocuments != null)
            {
                //Remove any documents that have been deleted
                foreach (var document in documents.Reverse<JobDocument>())

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Accidents/ViewAccident.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Accidents.AccidentViewModel

@{
    ViewBag.Title = "Accident Details";
}
@section contentHeader
{
    <h1>Accident Details</h1>
}
<div class="accident">
    
    @using (Bootstrap.BeginHorizontalForm(new { enctype = "multipart/form-data" }))
    {
        <div class="primary-actions">
            @if(Model.WorkInstructionID != null)
            {
                @Html.ActionLink("Cancel", "Details", "WorkInstructionDetails", new { id = Model.WorkInstructionID }, new { @class = "btn" })
            }
            else if (Model.JobID != null)
            {
                @Html.ActionLink("Cancel", "Update", "Job", new { id = Model.JobID }, new { @class = "btn" })
            }
            
        </div>
        <div class="masonry">
            <div class="span6 control-collection">
                <fieldset>
                    <legend>Accident Details</legend>
                    <div id="accident">
                        @Html.HiddenFor(m => m.AccidentID)
                        @Bootstrap.TextBoxFor(m => m.AccidentDate, new { @readonly = "readonly"})
                        @Bootstrap.TextAreaFor(m => m.AccidentDescription, new { @readonly = "readonly"})
                        @Bootstrap.TextBoxFor(m => m.Location, new { @readonly = "readonly"})
                        @Bootstrap.TextBoxFor(m => m.PeopleInvolved, new { @readonly = "readonly"})
                        @Bootstrap.TextBoxFor(m => m.PersonsReporting, new { @readonly = "readonly"})
                        @Bootstrap.TextBoxFor(m => m.Registrations, new { @readonly = "readonly"})
                        @Bootstrap.TextBoxFor(m => m.Witnesses, new { @readonly = "readonly"})
                        @Bootstrap.TextBoxFor(m => m.ActionTaken, new { @readonly = "readonly" })
                    </div>
                    
                </fieldset>
            </div>

            <div class="span6 control-collection">
                <fieldset>
                    <legend>Accident Photos</legend>
                    <div id="accidentPhotos">
                        
                    </div>
                    
                </fieldset>
            </div>
        </div>
    }
</div>

@section scripts{
    <script type="text/javascript">

        var photos = null;

        $(function () {

            photos = new triangle.ui.table('#accidentPhotos', '/Contract/Accidents/GetAccidentPhotos', 5, { accidentID: $("#AccidentID").val() });
            photos.searchBarExpandedSize = 300;
        });
    </script>
    
}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Accidents/WithShifts.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Accidents.AccidentViewModel

@{
    ViewBag.Title = "Accidents With Shifts";
}

@section contentHeader
{
    <h1>Accidents With Shifts</h1>
}
<div class="overview">
    <div class="primary-actions"></div>
    <div id="current">
    </div>
    <span class="clearfix"></span>
</div>
@section scripts{

    <script type="text/javascript">
        var accidents = null;

        $(function () {
            accidents = new triangle.ui.table('#current', '/Contract/Accidents/AccidentsWithShifts', 50);
        });

    </script>

}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Accidents/WithoutShifts.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Accidents.AccidentViewModel

@{
    ViewBag.Title = "Accidents Without Shifts";
}

@section contentHeader
{
    <h1>Accidents Without Shifts</h1>
}
<div class="overview">
    <div class="primary-actions"></div>
    <div id="current">
    </div>
    <span class="clearfix"></span>
</div>
@section scripts{

    <script type="text/javascript">
        var accidents = null;

        $(function () {
            accidents = new triangle.ui.table('#current', '/Contract/Accidents/AccidentsWithoutShifts', 50);
        });

    </script>

}