Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/Timesheets/TimesheetRecordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets
{
    public class TimesheetRecordViewModel
    {
        public Guid TimesheetRecordID { get; set; }
        public Guid TimesheetID { get; set; }
        public Guid EmployeeID { get; set; }
        public Guid ShiftID { get; set; }
        public string ShiftDate { get; set; }

        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }

        public int StartHour { get; set; }
        public int StartMin { get; set; }

        public int FinishHour { get; set; }
        public int FinishMin { get; set; }

        public DateTime WeekStart { get; set; }

        public string WorkInstruction { get; set; }

        public int WorkedHours { get; set; }
        [Range(0, 59, ErrorMessage = "Worked Mins must be between 0 and 59")]
        public int WorkedMins { get; set; }
        public int BreakHours { get; set; }
        [Range(0, 59, ErrorMessage = "Break Mins must be between 0 and 59")]
        public int BreakMins { get; set; }
        public int TravelHours { get; set; }
        [Range(0, 59, ErrorMessage = "Travel Mins must be between 0 and 59")]
        public int TravelMins { get; set; }

        public bool IPVAllowance { get; set; }
        public bool OnCallAllowance { get; set; }
        public bool PaidBreakAllowance { get; set; }
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/ViewModels/Timesheets/TimesheetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets
{
    public class TimesheetViewModel
    {
        public Guid TimesheetID { get; set; }
        public Guid EmployeeID { get; set; }        
    }
}

Bespoke/FMConway.MVCApp/Areas/Contract/Controllers/TimesheetController.cs
using FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets;
using FMConway.MVCApp.Bootstrap.Collections;
using FMConway.MVCApp.Bootstrap.Collections.Lookup;
using FMConway.MVCApp.Controllers;
using FMConway.MVCApp.Attributes;
using FMConway.MVCApp.Menu;
using FMConway.Services.Collections.Paging;
using FMConway.Services.Timesheets.Interfaces;
using FMConway.Services.Timesheets.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMConway.MVCApp.Areas.Contract.Controllers
{
    [Users(Users.UserTypes.Contractor)]
    [NavigationMenu("Timesheets", 40, "fa fa-clock", "Administrator, Supervisor, Manager, Timesheets")]
    public class TimesheetController : BaseController
    {
        ITimesheetService _timesheetService;

        public TimesheetController(ITimesheetService timesheetService)
        {
            _timesheetService = timesheetService;
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Timesheets")]
        [NavigationMenuItem(10, "fa fa-calendar-day")]
        public ActionResult Daily()
        {
            return View();
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Timesheets")]
        [NavigationMenuItem(10, "fa fa-calendar-week")]
        public ActionResult Weekly()
        {
            return View();
        }

        #region Lists

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult ActiveDailyTimesheets(int rowCount, int page, string query)
        {
            var results = _timesheetService.GetActiveDailyTimesheetsPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            var model = new PagedTable
            {
                Page = results.Page,
                PageCount = results.PageCount,
                ColumnHeaders = new string[]
                {
                    "Date",
                    "Employee",
                    "Number Of Shifts",
                    "Worked",
                    "Break",
                    "Travel"
                },
                Rows = results.Data.Select(s => new TableRow
                {
                    TableData = new string[]
                    {
                        s.WeekStart.ToShortDateString(),
                        s.EmployeeName,
                        s.NumberOfShifts.ToString(),
                        TimeSpan.FromMinutes((s.WorkedHours * 60) + s.WorkedMins).ToString(@"hh\:mm"),
                        TimeSpan.FromMinutes((s.BreakHours * 60) + s.BreakMins).ToString(@"hh\:mm"),
                        TimeSpan.FromMinutes((s.TravelHours * 60) + s.TravelMins).ToString(@"hh\:mm"),
                    },
                }).ToList()
            };

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, WorkInstructions")]
        public ActionResult ActiveTimesheetsAll(int rowCount, int page, string query)
        {
            PagedResults<TimesheetModel> results = null;

            results = _timesheetService.GetAllActiveTimesheetsPaged(rowCount, page, HttpUtility.HtmlEncode(query));

            PagedTable model = TimesheetListOverviewTable(results, new List<Func<TimesheetModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Timesheet")]
        public ActionResult ActiveTimesheets(int rowCount, int page, string query, Guid employeeID)
        {
            PagedResults<TimesheetModel> results = _timesheetService.GetActiveTimesheetsPaged(rowCount, page, HttpUtility.HtmlEncode(query), employeeID);

            PagedTable model = TimesheetOverviewTable(results, new List<Func<TimesheetModel, TableAction>>() { updateAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator, Supervisor, Manager, Timesheet")]
        public ActionResult ActiveTimesheetRecords(int rowCount, int page, string query, Guid timesheetID)
        {
            PagedResults<TimesheetRecordModel> results = _timesheetService.GetActiveTimesheetRecordsPaged(rowCount, page, HttpUtility.HtmlEncode(query), timesheetID);

            PagedTable model = TimesheetRecordOverviewTable(results, new List<Func<TimesheetRecordModel, TableAction>>() { viewTimeSheetAction });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Table Overviews

        private PagedTable TimesheetRecordOverviewTable(PagedResults<TimesheetRecordModel> results, List<Func<TimesheetRecordModel, TableAction>> actions)
        {
            PagedTable model = new PagedTable()
            {
                Page = results.Page,
                PageCount = results.PageCount,
                ColumnHeaders = new string[]
                {
                    "Start Time",
                    "End Time",
                    "Worked",
                    "Break",
                    "Travel",
                    "Task(s)"
                },
                Rows = results.Data.Select(s => new TableRow
                {
                    TableData = new string[]
                    {
                        s.StartTime.ToString(),
                        s.EndTime.ToString(),
                        TimeSpan.FromMinutes((s.WorkedHours * 60) + s.WorkedMins).ToString(@"hh\:mm"),
                        TimeSpan.FromMinutes((s.BreakHours * 60) + s.BreakMins).ToString(@"hh\:mm"),
                        TimeSpan.FromMinutes((s.TravelHours * 60) + s.TravelMins).ToString(@"hh\:mm"),
                        s.WorkInstruction
                    },
                    Actions = actions.Select(action => action(s)).ToList()
                }).ToList()
            };

            return model;
        }

        private PagedTable TimesheetOverviewTable(PagedResults<TimesheetModel> results, List<Func<TimesheetModel, TableAction>> actions)
        {
            PagedTable model = new PagedTable()
            {
                Page = results.Page,
                PageCount = results.PageCount,
                ColumnHeaders = new string[] { "Week Start", "Number Of Shifts", "Worked Hours", "Worked Mins"},
                Rows = results.Data.Select(s => new TableRow
                {
                    TableData = new string[] { s.WeekStart.ToShortDateString(), s.NumberOfShifts.ToString(), s.WorkedHours.ToString(), s.WorkedMins.ToString() },
                    Actions = actions.Select(action => action(s)).ToList()
                }).ToList()
            };

            return model;
        }

        private PagedTable TimesheetListOverviewTable(PagedResults<TimesheetModel> results, List<Func<TimesheetModel, TableAction>> actions)
        {
            //TimeSpan.FromMinutes(minutes);
            //return timespan.ToString(@"hh\:mm");

            PagedTable model = new PagedTable()
            {
                Page = results.Page,
                PageCount = results.PageCount,
                ColumnHeaders = new string[]
                {
                    "Week Start",
                    "Employee",
                    "Number Of Shifts",
                    "Worked",
                    "Break",
                    "Travel"
                },
                Rows = results.Data.Select(s => new TableRow
                {
                    TableData = new string[]
                    {
                        s.WeekStart.ToShortDateString(),
                        s.EmployeeName,
                        s.NumberOfShifts.ToString(),
                        TimeSpan.FromMinutes((s.WorkedHours * 60) + s.WorkedMins).ToString(@"hh\:mm"),
                        TimeSpan.FromMinutes((s.BreakHours * 60) + s.BreakMins).ToString(@"hh\:mm"),
                        TimeSpan.FromMinutes((s.TravelHours * 60) + s.TravelMins).ToString(@"hh\:mm"),
                    },
                    Actions = actions.Select(action => action(s)).ToList()
                }).ToList()
            };

            return model;
        }

        #endregion

        #region Views

        public ActionResult CreateTimesheet(Guid employeeID)
        {
            TimesheetRecordViewModel model = new TimesheetRecordViewModel() 
            {
                EmployeeID = employeeID,
                StartHour = 9,
                FinishHour = 17,
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreateTimesheet(TimesheetRecordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.ShiftID.Equals(Guid.Empty))
            {
                ModelState.AddModelError("TimesheetRecord", "No shifts exist.");
                return View(model);
            }

            DateTime date;
            if (DateTime.TryParse(model.ShiftDate, out date))
            {
                model.StartTime = date;
            }
            else
            {
                ModelState.AddModelError("ShiftDate", "Please try again.");
                return View(model); 
            }

            if (model.BreakHours == 0 && model.BreakMins == 0 && model.WorkedHours == 0 && model.WorkedMins == 0)
            {
                ModelState.AddModelError("Empty", "Please enter some hours.");
                return View(model);
            }

            Guid timesheetID = _timesheetService.CreateTimesheet(model.EmployeeID, model.StartTime);

            if (timesheetID != Guid.Empty)
            {
                TimesheetRecordModel record = new TimesheetRecordModel() 
                {                    
                    TimesheetID = timesheetID,
                    StartTime = model.StartTime.Date.AddHours(model.StartHour).AddMinutes(model.StartMin),

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Timesheet/CreateTimesheet.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets.TimesheetRecordViewModel

@{
    ViewBag.Title = "Create Timesheet";
}

@section contentHeader
{
    <h1>Create Timesheet</h1>
}

<div class="activity">
    @Bootstrap.Validation.ValidationSummary()
    @using (Bootstrap.BeginHorizontalForm(new { enctype = "multipart/form-data" }))
    {
        <div class="primary-actions">
            @Html.ActionLink("Cancel", "Update", "Employee", new { id = Model.EmployeeID }, new { @class = "btn" })
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
        
        <div class="masonry">
            <div class="span6 control-collection">
                <fieldset>
                    <legend>Timesheet Record</legend>
                    @Html.HiddenFor(m => m.EmployeeID)
                    @Bootstrap.LookupFor(m => m.ShiftID, m => m.ShiftDate, "Shift")
                    <div class="control-group time">
                        <label for="#Start-Hour" class="control-label">Start Time</label>
                        <div class="controls">
                            <input id="Start-Hour" name="StartHour" class="time-spinner spinner" type="number" min="0" max="23" value="@Model.StartHour" />
                            <input id="Start-Min" name="StartMin" class="time-spinner spinner" type="number" min="0" max="59"  value="@Model.StartMin"  />
                        </div>
                    </div>
                    <div class="control-group time">
                        <label for="#Finish-Hour" class="control-label">Finish Time</label>
                        <div class="controls">
                            <input id="Finish-Hour" name="FinishHour" class="time-spinner spinner" type="number" min="0" max="23" value="@Model.FinishHour" />
                            <input id="Finish-Min" name="FinishMin" class="time-spinner spinner" type="number" min="0" max="59"  value="@Model.FinishMin"  />
                        </div>
                    </div>      
                               
                    @Bootstrap.TextBoxFor(m => m.WorkedHours, new { label = "Working Hours" })
                    @Bootstrap.TextBoxFor(m => m.WorkedMins, new { label = "Working Mins" })
                    @Bootstrap.TextBoxFor(m => m.BreakHours, new { label = "Break Hours" })
                    @Bootstrap.TextBoxFor(m => m.BreakMins, new { label = "Break Mins" })

                    @Bootstrap.CheckBoxFor(m => m.IPVAllowance)
                    @Bootstrap.CheckBoxFor(m => m.PaidBreakAllowance)
                    @Bootstrap.CheckBoxFor(m => m.OnCallAllowance)
                    
                </fieldset>
            </div>
            
        </div> 
    }
</div>
@section scripts{
    <script type="text/javascript">
        var shiftLookup = null;

        $(function ()
        {
            shiftLookup = new triangle.ui.lookup("#ShiftID" /*ID*/, "/Contract/Timesheet/GetShiftsForEmployeeLookup?employeeID=" + $('#EmployeeID').val() /*URL*/, 7/*RowCount*/, false /*IsMultiSelect*/);
            shiftLookup.UrlParameters = function () {
                return { employeeID: $("#EmployeeID").val() };
            }
        });
    </script>
}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Timesheet/CreateTimesheetRecord.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets.TimesheetRecordViewModel

@{
    ViewBag.Title = "Create Timesheet Record";
}

@section contentHeader
{
    <h1>Create Timesheet Record for Week Beginning @Model.WeekStart.Day.ToString()/@Model.WeekStart.Month.ToString()/@Model.WeekStart.Year.ToString()</h1>
}

<div class="activity">
    @Bootstrap.Validation.ValidationSummary()
    @using (Bootstrap.BeginHorizontalForm(new { enctype = "multipart/form-data" }))
    {
        <div class="primary-actions">
            @Html.ActionLink("Cancel", "UpdateTimesheet", "Timesheet", new { id = Model.TimesheetID }, new { @class = "btn" })
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
        
        <div class="masonry">
            <div class="span6 control-collection">
                <fieldset>
                    <legend>Timesheet Record</legend>
                    @Html.HiddenFor(m => m.EmployeeID)
                    @Html.HiddenFor(m => m.TimesheetID)
                    @Bootstrap.LookupFor(m => m.ShiftID, m => m.ShiftDate, "Shift")
                    @Bootstrap.TextBoxFor(m => m.WorkedHours, new { label = "Working Hours"})
                    @Bootstrap.TextBoxFor(m => m.WorkedMins, new { label = "Working Mins"})
                    @Bootstrap.TextBoxFor(m => m.BreakHours, new { label = "Break Hours"})
                    @Bootstrap.TextBoxFor(m => m.BreakMins, new { label = "Break Mins"})
                    @Bootstrap.TextBoxFor(m => m.TravelHours, new { label = "Travel Hours"})
                    @Bootstrap.TextBoxFor(m => m.TravelMins, new { label = "Travel Mins"})

                    @Bootstrap.CheckBoxFor(m => m.IPVAllowance)
                    @Bootstrap.CheckBoxFor(m => m.PaidBreakAllowance)
                    @Bootstrap.CheckBoxFor(m => m.OnCallAllowance)
                </fieldset>
            </div>
            
        </div> 
    }
</div>
@section scripts{
    <script type="text/javascript">
        var shiftLookup = null;

        $(function ()
        {
            shiftLookup = new triangle.ui.lookup("#ShiftID" /*ID*/, "/Contract/Timesheet/GetShiftsForTimesheetLookup?timesheetID=" + $("#TimesheetID").val() /*URL*/, 7/*RowCount*/, false /*IsMultiSelect*/);
            //shiftLookup.UrlParameters = function () {
            //    return {
            //        timesheetID: $("#TimesheetID").val()
            //    };
            //}
        });
    </script>
}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Timesheet/Daily.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets.TimesheetViewModel

@{
    ViewBag.Title = "Daily Timesheets";
}

@section contentHeader
{
    <h1>Daily Timesheets</h1>
}

<div class="overview">
    <div class="primary-actions">

    </div>
    <div id="current">

    </div>

</div>

@section scripts{
    <script type="text/javascript">

        var activeTimesheets = null;

        $(function () {
            activeTimesheets = new triangle.ui.table('#current', '/Contract/Timesheet/ActiveDailyTimesheets', 50);
        });

    </script>
}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Timesheet/UpdateTimesheet.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets.TimesheetViewModel

@{
    ViewBag.Title = "View Timesheet";
}

@section contentHeader
{
    <h1>View Timesheet</h1>
}

<style>
    #activeTimesheetRecords table tr {
        white-space: nowrap;
    }
</style>

<div class="activity">
    @Bootstrap.Validation.ValidationSummary()
    @using (Bootstrap.BeginHorizontalForm(new { enctype = "multipart/form-data" }))
    {
        <div class="primary-actions">
            @if (Model.EmployeeID != Guid.Empty)
            {
                @Html.ActionLink("Cancel", "Update", "Employee", new { id = Model.EmployeeID },new { @class = "btn" })
            }
            else
            {
                @Html.ActionLink("Cancel", "Active", "Timesheet",new { @class = "btn" })
            }
            <input type="submit" class="btn btn-primary" value="Save" />
            @Html.ActionLink("Print", "PrintTimesheet", "Timesheet", new { id = Model.TimesheetID }, new { @class = "btn btn-primary" })
        </div>
        @Html.HiddenFor(m => m.TimesheetID)
        <div class="masonry">
            <div class="span8 control-collection">
                <fieldset>
                    <legend>Timesheet Records</legend>
                    <div class="tab-pane table-Actions-Spacing" id="activeTimesheetRecords">
                    </div>
                
                    <div class="actions">@Html.ActionLink("Add Record", "CreateTimesheetRecord", "Timesheet", new { timesheetID = Model.TimesheetID }, new { @class = "btn" })
                    </div>
                </fieldset>
            </div>
            
        </div> 
    }
</div>
@section scripts{
    <script type="text/javascript">
        var timesheetRecords = null;

        $(function () {

            timesheetRecords = new triangle.ui.table('#activeTimesheetRecords', '/Contract/Timesheet/ActiveTimesheetRecords', 5, { timesheetID: $("#TimesheetID").val() });
            timesheetRecords.searchBarExpandedSize = 300;

        });
    </script>
}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Timesheet/UpdateTimesheetRecord.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets.TimesheetRecordViewModel

@{
    ViewBag.Title = "View Timesheet Record";
}

@section contentHeader
{
    <h1>View Timesheet Record</h1>
}

<div class="activity">
    @Bootstrap.Validation.ValidationSummary()
    @using (Bootstrap.BeginHorizontalForm(new { enctype = "multipart/form-data" }))
    {
        <div class="primary-actions">
            @Html.ActionLink("Cancel", "UpdateTimesheet", "Timesheet", new { id = Model.TimesheetID }, new { @class = "btn" })
            <input type="submit" class="btn btn-primary" value="Save" />            
        </div>
        @Html.HiddenFor(m => m.TimesheetID)
        @Html.HiddenFor(m => m.TimesheetRecordID)
        <div class="masonry">
            <div class="span8 control-collection">
                <fieldset>
                    <legend>Timesheet Record</legend>
                    @Bootstrap.TextBoxFor(m => m.StartTime, new { disabled = "disabled" })
                    @Bootstrap.TextBoxFor(m => m.EndTime, new { disabled = "disabled" })
                    @Bootstrap.TextBoxFor(m => m.WorkInstruction, new { disabled = "disabled" })
                    @Bootstrap.TextBoxFor(m => m.WorkedHours, new { label = "Working Hours"})
                    @Bootstrap.TextBoxFor(m => m.WorkedMins, new { label = "Working Mins"})
                    @Bootstrap.TextBoxFor(m => m.BreakHours, new { label = "Break Hours"})
                    @Bootstrap.TextBoxFor(m => m.BreakMins, new { label = "Break Mins"})
                    @Bootstrap.TextBoxFor(m => m.TravelHours, new { label = "Travel Hours"})
                    @Bootstrap.TextBoxFor(m => m.TravelMins, new { label = "Travel Mins"})

                    @Bootstrap.CheckBoxFor(m => m.IPVAllowance)
                    @Bootstrap.CheckBoxFor(m => m.PaidBreakAllowance)
                    @Bootstrap.CheckBoxFor(m => m.OnCallAllowance)
                </fieldset>
            </div>
            
        </div> 
    }
</div>
@section scripts{
    <script type="text/javascript">
        
    </script>
}

Bespoke/FMConway.MVCApp/Areas/Contract/Views/Timesheet/Weekly.cshtml
@model FMConway.MVCApp.Areas.Contract.ViewModels.Timesheets.TimesheetViewModel

@{
    ViewBag.Title = "Weekly Timesheets";
}

@section contentHeader
{
    <h1>Weekly Timesheets</h1>
}

<div class="overview">
    <div class="primary-actions">

    </div>
    <div id="current">

    </div>
</div>

@section scripts{
    <script type="text/javascript">

        var activeTimesheets = null;

        $(function () {
            activeTimesheets = new triangle.ui.table('#current', '/Contract/Timesheet/ActiveTimesheetsAll', 50);
        });

    </script>
}